site_name: Kuberlab Documentation
theme: readthedocs

pages:
- Home: 'index.md'
- Datasets: 
  - 'Datasets': 'Datasets/datasets.md'
  - 'How to use': 'Datasets/usage.md'
  - 'Comands': "Datasets/commands.md"
- Catalog:
- Settings:
- Resources:
- Projects: 


