site_name: kibernetika.ai 
theme: readthedocs
copyright: Copyright 2018 Kibernetika Inc.
dev_addr: 0.0.0.0:8000
google_analytics: ['UA-36723568-3', 'mkdocs.org']
pages:
- Home: 'index.md'
- Settings:
  - 'User': 'Settings/user.md'
  - 'Organization': 'Settings/organization.md'
  - 'Billing': 'Settings/billing.md'
- Projects: 
  - 'Create New Project': 'Projects/Create New Project.md'
  - 'Working With Projects.md': 'Projects/Working With Projects.md'
- Catalog:
  - 'Catalog': 'Catalog/Catalog.md'
  - 'Work With Catalog': 'Catalog/Work With Catalog.md'
  - 'Add New Project Template': 'Catalog/Add New Project Template.md'
  - 'Add New Application': 'Catalog/Add New Application.md'
- Datasets: 
  - 'Datasets': 'Datasets/datasets.md'
  - 'Usage': 'Datasets/usage.md'
  - 'Comands': "Datasets/commands.md"
- Resources:
  - 'Infrastructure': 'Resources/infrastructure.md'
  - 'Clusters': 'Resources/Clusters.md'
  - 'Storage': 'Resources/Kuberlab Storage.md'
- Tutorials:
  - 'Project Page Tour': 'Tutorials/project_page.md'
  - 'Using OpenVINO': 'Tutorials/openvino.md'
- About:
  - 'Copyright': 'About/about.md'


