site_name: Kuberlab Documentation
theme: readthedocs

pages:
- Home: 'index.md'
- Datasets: 
  - 'Datasets': 'Datasets/index.md'
  - 'How to use': 'Datasets/usage.md'
  - 'Comands': "Datasets/commands.md"
