site_name: Kibernetika Documentation 
theme: readthedocs
copyright: Copyright 2018 Kibernetika Inc.
dev_addr: 0.0.0.0:8000
markdown_extensions:
- toc:
    permalink: "#"
google_analytics: ['UA-36723568-3', 'mkdocs.org']
pages:
- 'Home': 'index.md'
- 'Settings':
  - 'User': 'settings/user.md'
  - 'Organization': 'settings/organization.md'
  - 'Billing': 'settings/billing.md'
- 'Projects':
  - 'Create New Project': 'projects/create-new-project.md'
  - 'Working With Projects': 'projects/working-with-projects.md'
- 'Datasets':
  - 'Datasets Managment': 'datasets/datasets.md'
- 'Serving':
  - 'Start serving': 'serving/serving-start.md'
  - 'Serving tool': 'serving/kibernetika-serving.md'
- 'Resources':
  - 'Storage': 'resources/kibernetika-storage.md'
- 'Tools':
  - 'kdataset': 'tools/kdataset.md'
  - 'kibernetika-serving': 'serving/kibernetika-serving.md'
- 'Tutorials':
  - 'Project Page Tour': 'tutorials/project-page.md'
  - 'Using OpenVINO': 'tutorials/openvino.md'
- 'HowTo':
  - 'Train CIFAR-10 Model from scratch using Kibernetika.AI': 'how-to/cifar-10.md'
- 'About':
  - 'Copyright': 'about/about.md'
